# Generated by Django 5.2.5 on 2025-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_achievement_context_alter_feature_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(),
        ),
    ]
